### ISSUE TITLE
public interface declaration causes build failure

### ISSUE THREAD

**Issue by felixti** [bgianfo/pr-dash#9]
Syntax error at build application 

![image](https://user-images.githubusercontent.com/3665226/66792185-f8b79d00-eecd-11e9-82ae-eeb934f0382c.png)
**Solution:**
Remove _public_ modifier from interface methods declarations.

**Comment by bgianfo** [comment]
How are you building, can you share your dotnet --version?

**Comment by bgianfo** [comment]
Guess it doesn't matter how you build anyway, just curious how it doesn't fail on my setup.

Pushed the fix to master, thanks for reporting.

**Comment by felixti** [comment]
![image](https://user-images.githubusercontent.com/3665226/66792647-05d58b80-eed0-11e9-86ba-5cd1dcbec70e.png)
